### ISSUE TITLE
Support of Python

### ISSUE THREAD

**Issue by piiiiiiie** [jjiantong/FastPGM#3]
Hi. I'm wondering if this C++ project has a Python API that allows me to call its functions using Python. It would be helpful.

Thanks.

**Comment by jjiantong** [comment]
Hi Piiiiiiie,

Thanks for the suggestion. We have added the support of Python. You can now clone the latest version of FastBN (with the ```--recursive``` option), and then install and run via
```
cd FastBN/python
pip install .
python3 pyfastbn.py
```

The parameters are in ```FastBN/python/config.json```.

We have also updated the documentation correspondingly. Please see https://fastbn.readthedocs.io/en/latest/python.html for details.

Cheers
